// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.0.1.0")]
[assembly: AssemblyFileVersionAttribute("1.0.1.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.1.0")]
[assembly: AssemblyConfigurationAttribute("Built on 09/03/2018 at 14:20:20 from revision 0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "1.0.1.0";
        internal const System.String AssemblyFileVersion = "1.0.1.0";
        internal const System.String AssemblyInformationalVersion = "1.0.1.0";
        internal const System.String AssemblyConfiguration = "Built on 09/03/2018 at 14:20:20 from revision 0";
    }
}
