// Auto-generated by fake script
namespace Energy.ProviderAdapter
{
    public static class Provider
    {
        public const string Name = "EnergyHelpLine";
        public const string BrandCodePrefix = "EHL";
    }
}
